### ISSUE TITLE
AttributeError: 'Lyrics' object has no attribute 'shift'

### ISSUE THREAD

**Issue by PlaylistsTrance** [doakey3/pylrc#13]
I tried to follow your "Usage" example but when I do `subs.shift(milliseconds=-1100)` I get the attribute error that Lyrics doesn't have the attribute shift.
Am I doing something wrong? Or if it got removed, could it be readded?

**Comment by SimonIT** [comment]
I think the example is wrong. If you look into [this](https://github.com/doakey3/pylrc/blob/master/pylrc/classes.py) file, you can see, that only LyricLines got the shift method. You can simply iterate over the Lyrics object to shift each line

**Comment by PlaylistsTrance** [comment]
Thanks for the quick response, how does one iterate over the Lyrics object?

**Comment by SimonIT** [comment]
For example like this:
```python3
for sub in pylrc.parse(lrc_string):
    sub.shift(milliseconds=-1100)
```

**Comment by PlaylistsTrance** [comment]
Hm, where should this be executed? In the terminal? Because I'm not sure where to call toSRT() after this.

**Comment by PlaylistsTrance** [comment]
I'd like to have a `def shift(self, minutes=0, seconds=0, milliseconds=0)` inside `class Lyrics(list)` which then iterates over its lines, if possible. Not sure if your for loop could be used there.

**Comment by SimonIT** [comment]
Do you can program? It seems that you aren't familiar with the basics...
```python3
lyrics = pylrc.parse(lrc_string)
for sub in lyrics:
    sub.shift(milliseconds=-1100)
lyrics.toSRT()
```

**Comment by PlaylistsTrance** [comment]
Yeah, just not too familiar with Python yet. Thanks.

**Comment by PlaylistsTrance** [comment]
Just wondering if you've tried this yourself. I get a list index out of range when converting to SRT
```python
>>> lyrics.toSRT()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/d/tools/python/pylrc/classes.py", line 82, in toSRT
    if not self[-1].text.rstrip() == "":
IndexError: list index out of range```
As this was in the original code I didn't question the negative index, but is this the issue or is my lrc somehow the problem?

**Comment by SimonIT** [comment]
No, I didn't tried it. I didn't used the srt functionality of this lib. Can you provide the lrc so I can find the problem? Maybe it's a bug in this lib

**Comment by PlaylistsTrance** [comment]
Sure. https://pastebin.com/jbqyGQqE I doubt it's the [id:...] thing because that's ignored in the parser, right?

**Comment by SimonIT** [comment]
Yes, the id gets ignored. I don't got any problem. This is my result: https://pastebin.com/KKuXYWYx

**Comment by PlaylistsTrance** [comment]
```
>>> lrc_file = open('/d/Music/Lyrics/Lovelyz - WoW!.srt')
>>> lrc_string = ''.join(lrc_file.readlines())
>>> lrc_file.close()
>>> lyrics = pylrc.parse(lrc_string)
>>> for sub in lyrics:
...   sub.shift(milliseconds=-1100)
...
>>> srt = lyrics.toSRT()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/d/tools/python/pylrc/classes.py", line 82, in toSRT
    if not self[-1].text.rstrip() == "":
IndexError: list index out of range
>>>
```
Am I doing something stupid here?

**Comment by PlaylistsTrance** [comment]
Oh by the way, the new timestamps have negative millisecond values...

**Comment by SimonIT** [comment]
Maybe use `open('/d/Music/Lyrics/Lovelyz - WoW!.srt', "r", encoding="UTF-8")`? Is the file ending really srt? Yeah, the shift method needs an improvement

**Comment by PlaylistsTrance** [comment]
Same problem after doing the same steps with your new `open(...)`. It's definitely a .srt file, it has "SRT File" at the "Type" column in explorer, just as proof haha.

**Comment by PlaylistsTrance** [comment]
Oh wait that's the problem isn't it... I should be using the .lrc file......

**Comment by PlaylistsTrance** [comment]
Alright, so that was obviously dumb, but now I have the following issue ```
>>> lrc_file = open('/d/Music/Music/K-Pop/Lovelyz/[2017.02.26] Lovelyz - R U Ready/Lovelyz - WoW!.lrc')
>>> lrc_string = ''.join(lrc_file.readlines())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
Any idea why you didn't have this problem? (Same happens when adding `"r", encoding="UTF-8")

**Comment by SimonIT** [comment]
Yes, it must be a lrc file. If declaring the encoding results in an error than use your open line

**Comment by PlaylistsTrance** [comment]
Problem is both gave the same output, seems like utf-8 is default.

**Comment by SimonIT** [comment]
Than you have to find out the encoding of the file

**Comment by PlaylistsTrance** [comment]
Yep, for some reason that was UCS-2 LE BOM, thanks again. Just one more question from a Python noob, how do I save that srt variable to a file?

**Comment by PlaylistsTrance** [comment]
Nvm, ```bash
>>> f = open('/d/Downloads/Lovelyz - WoW! 3.srt', 'w')
>>> f.write(srt)
4286
>>> f.close()```
worked.
