### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by SimonIT** [doakey3/pylrc#9]
My last PR #8 fixed an annoying bug for me. It would be kind if you release this lib with this PR.
Thanks

**Comment by doakey3** [comment]
Yup sorry about that, I must have forgotten to do it. I just tested it with pip and it seems to install fine with your updates.

**Comment by SimonIT** [comment]
Again please

**Comment by doakey3** [comment]
OK, I just uploaded it.

**Comment by SimonIT** [comment]
Thanks
